language: r

warnings_are_errors: false

addons:
  apt:
    update: true

before_install:
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev libnetcdf-dev netcdf-bin
